name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: aria2b

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ReleaseTag
      - name: Set Version
        id: set-version
        run: |
          version=$(date +"%y-%m-%d")
          echo "version=$version" >> $GITHUB_OUTPUT
          echo $version
          echo "status=success" >> $GITHUB_OUTPUT

      # Build and push
      - name: Build dockerfile
        if: steps.set-version.outputs.status == 'success'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            awsl1414/aria2:a2b-stable-${{ steps.set-version.outputs.version }}
            awsl1414/aria2:a2b-latest
