#!/usr/bin/with-contenv bash

#修改secret
ARIA2_RPC_SECRET_CONF_VAL=$(grep ^rpc-secret= /config/aria2.conf | sed 's/\(.*\)=//g' | sed ":a;N;s/\n//g;ta")
if [ -n "$ARIA2_RPC_SECRET" ]; then
  if [ "$ARIA2_RPC_SECRET_CONF_VAL" != "$ARIA2_RPC_SECRET" ]; then
    if [ "$(grep -c ^rpc-secret= /config/aria2.conf)" -gt 0 ]; then
      sed -i 's/^rpc-secret='"$ARIA2_RPC_SECRET_CONF_VAL"'/rpc-secret='"$ARIA2_RPC_SECRET"'/g' /config/aria2.conf
    else
      sed -i "$ a rpc-secret=$ARIA2_RPC_SECRET" /config/aria2.conf
    fi
  fi
else
  if [ -z "$ARIA2_RPC_SECRET_CONF_VAL" ] && [ "$(grep -c ^rpc-secret= /config/aria2.conf)" -gt 0 ]; then
    sed -i 's/^rpc-secret=/\#rpc-secret=/g' /config/aria2.conf
  fi
fi

#修改port
#listen-port and dht-listen-port
ARIA2_LISTEN_PORT_CONF_VAL=$(grep ^listen-port= /config/aria2.conf | sed 's/\(.*\)=//g' | sed ":a;N;s/\n//g;ta")
ARIA2_DHT_LISTEN_PORT_CONF_VAL=$(grep ^dht-listen-port= /config/aria2.conf | sed 's/\(.*\)=//g' | sed ":a;N;s/\n//g;ta")
if [ -n "$ARIA2_LISTEN_PORT" ] && { [ "$ARIA2_LISTEN_PORT_CONF_VAL" != "$ARIA2_LISTEN_PORT" ] || [ "$ARIA2_DHT_LISTEN_PORT_CONF_VAL" != "$ARIA2_LISTEN_PORT" ]; }; then

  if [ "$(grep -c ^listen-port= /config/aria2.conf)" -gt 0 ]; then
    sed -i 's/^listen-port='"$ARIA2_LISTEN_PORT_CONF_VAL"'/listen-port='"$ARIA2_LISTEN_PORT"'/g' /config/aria2.conf
  else
    sed -i "$ a listen-port=$ARIA2_LISTEN_PORT" /config/aria2.conf
  fi
  if [ "$(grep -c ^dht-listen-port= /config/aria2.conf)" -gt 0 ]; then
    sed -i 's/^dht-listen-port='"$ARIA2_DHT_LISTEN_PORT_CONF_VAL"'/dht-listen-port='"$ARIA2_LISTEN_PORT"'/g' /config/aria2.conf
  else
    sed -i "$ a dht-listen-port=$ARIA2_LISTEN_PORT" /config/aria2.conf
  fi
fi

#rpc-listen-port
ARIA2_RPC_LISTEN_PORT_CONF_VAL=$(grep ^rpc-listen-port= /config/aria2.conf | sed 's/\(.*\)=//g' | sed ":a;N;s/\n//g;ta")
if [ -n "$ARIA2_RPC_LISTEN_PORT" ] && [ "$ARIA2_RPC_LISTEN_PORT_CONF_VAL" != "$ARIA2_RPC_LISTEN_PORT" ]; then
  if [ "$(grep -c ^rpc-listen-port= /config/aria2.conf)" -gt 0 ]; then
    sed -i 's/^rpc-listen-port='"$ARIA2_RPC_LISTEN_PORT_CONF_VAL"'/rpc-listen-port='"$ARIA2_RPC_LISTEN_PORT"'/g' /config/aria2.conf
  else
    sed -i "$ a rpc-listen-port=$ARIA2_RPC_LISTEN_PORT" /config/aria2.conf
  fi
fi

#修改AriaNg替换js字符串(添加设置的token和rpcPort值为默认。)
cp /usr/local/aria2/AriaNg/js/defaultsjs/aria-ng* /usr/local/aria2/AriaNg/js/
if [ "$ARIANG_RPC_SECRET_AUTO" == "true" ]; then
  if [ -n "$ARIA2_RPC_SECRET" ]; then
    ARIA2_RPC_SECRET_ARIANg_VAL=$(echo -n "$ARIA2_RPC_SECRET" | base64)
    sed -i 's/secret:""/secret:"'"$ARIA2_RPC_SECRET_ARIANg_VAL"'"/g' /usr/local/aria2/AriaNg/js/aria-ng*
  else
    ARIA2_RPC_SECRET_CONF_VAL=$(grep ^rpc-secret= /config/aria2.conf | sed 's/\(.*\)=//g' | sed ":a;N;s/\n//g;ta")
    if [ -n "$ARIA2_RPC_SECRET_CONF_VAL" ]; then
      ARIA2_RPC_SECRET_ARIANg_VAL=$(echo -n "$ARIA2_RPC_SECRET_CONF_VAL" | base64)
      sed -i 's/secret:""/secret:"'"$ARIA2_RPC_SECRET_ARIANg_VAL"'"/g' /usr/local/aria2/AriaNg/js/aria-ng*
    fi
  fi
fi
if [ "$ARIANG_RPC_LISTEN_PORT_AUTO" == "true" ]; then
  if [ -n "$ARIA2_RPC_LISTEN_PORT" ]; then
    if [ "$ARIA2_RPC_LISTEN_PORT" != "6800" ]; then
      sed -i 's/rpcPort:"6800"/rpcPort:"'"$ARIA2_RPC_LISTEN_PORT"'"/g' /usr/local/aria2/AriaNg/js/aria-ng*
    fi
  else
    ARIA2_RPC_LISTEN_PORT_CONF_VAL=$(grep ^rpc-listen-port= /config/aria2.conf | sed 's/\(.*\)=//g' | sed ":a;N;s/\n//g;ta")
    if [ -n "$ARIA2_RPC_LISTEN_PORT_CONF_VAL" ] && [ "$ARIA2_RPC_LISTEN_PORT_CONF_VAL" != "6800" ]; then
      sed -i 's/rpcPort:"6800"/rpcPort:"'"$ARIA2_RPC_LISTEN_PORT_CONF_VAL"'"/g' /usr/local/aria2/AriaNg/js/aria-ng*
    fi
  fi
fi

# extra function
ON_DOWNLOAD_START=$(awk -F= '/^on-download-start=/ {print $2}' /config/aria2.conf)
if [ -z "$ON_DOWNLOAD_START" ]; then
  sed -i "s/.*on-download-start.*/on-download-start=\/script\/start.sh/" /config/aria2.conf
fi

ON_DOWNLOAD_STOP=$(awk -F= '/^on-download-stop=/ {print $2}' /config/aria2.conf)
if [ -z "$ON_DOWNLOAD_STOP" ]; then
  sed -i 's@^\(on-download-stop=\).*@\1/script/stop.sh@' /config/aria2.conf
fi

ON_DOWNLOAD_COMPLETE=$(awk -F= '/^on-download-complete=/ {print $2}' /config/aria2.conf)
if [ -z "$ON_DOWNLOAD_COMPLETE" ]; then
  sed -i 's@^\(on-download-complete=\).*@\1/script/completed.sh@' /config/aria2.conf
fi

ON_DOWNLOAD_PAUSE=$(awk -F= '/^on-download-pause=/ {print $2}' /config/aria2.conf)
if [ -z "$ON_DOWNLOAD_PAUSE" ]; then
  sed -i "s/.*on-download-pause.*/on-download-pause=\/script\/pause.sh/" /config/aria2.conf
fi

