#!/usr/bin/with-contenv bash

#设置时区
ln -sf /usr/share/zoneinfo/"$TZ" /etc/localtime
echo "$TZ" >/etc/timezone

#修改用户UID GID
groupmod -o -g "$GID" aria2
usermod -o -u "$UID" aria2

#修复权限
chown -R aria2:aria2 /config
chown -R aria2:aria2 /downloads
chown -R aria2:aria2 /usr/local/aria2

#脚本权限
chmod a+x /script/*

#设定trackers更新任务
if [ "$(grep -c updatetrackers.sh /var/spool/cron/crontabs/root)" -eq 0 ]; then
    echo "0       0       *       *       *       /usr/local/aria2/script/rpc_tracker.sh" >>/var/spool/cron/crontabs/root
    echo trackers更新任务已设定。
else
    echo trackers更新任务已存在。
fi

#启动更新trackers。
if [ "$ARIA2_TRACKERS_UPDATE_AUTO" == "true" ]; then
    /script/tracker.sh
fi

# set cron-restart-a2b
bash /script/cron-restart-a2b.sh